export const surveyCardsData = [
    {
      id: 1,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyNotStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 2,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyNotStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 3,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 4,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 5,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 6,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyStarted",
      totalResponse: 50,
      totalMembers: 250,
    },
    {
      id: 7,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 8,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 9,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 10,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 11,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 12,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "IncommingSurveyCompleted",
      totalResponse: 250,
      totalMembers: 250,
    },
  ];