export const surveyCardsData = [
    {
      id: 1,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Created",
      totalResponse: 0,
      totalMembers: 250,
    },
    {
      id: 2,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Live",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 3,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Live",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 4,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Live",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 5,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Live",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 6,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Live",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 7,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Draft",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 8,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Draft",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 9,
      date: "Nov 26, 2022",
      surveyName: "Academics survey",
      createdBy: "Office academics",
      surveyStatus: "Draft",
      totalResponse: 148,
      totalMembers: 250,
    },
    {
      id: 10,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Completed",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 11,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Completed",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 12,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Completed",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 13,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Completed",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 14,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Scheduled",
      totalResponse: 0,
      totalMembers: 250,
    },
    {
      id: 15,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Scheduled",
      totalResponse: 0,
      totalMembers: 250,
    },
    {
      id: 16,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Scheduled",
      totalResponse: 0,
      totalMembers: 250,
    },
    {
      id: 17,
      date: "Nov 26, 2022",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Scheduled",
      totalResponse: 0,
      totalMembers: 250,
    },
    {
      id: 18,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 19,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 20,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 21,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 22,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
    {
      id: 23,
      date: "6",
      surveyName: "Product thinking Activity",
      createdBy: "Personalized Skill team",
      surveyStatus: "Group surveys",
      totalResponse: 250,
      totalMembers: 250,
    },
  ];